/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'spain' at '4/05/17 21:22' with Gradle 2.14.1
 *
 * @author spain, @date 4/05/17 21:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
